//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABOUT
    {
        public int id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string sliderimage { get; set; }
        public Nullable<bool> status { get; set; }
        public string videoUrl { get; set; }
        public Nullable<bool> statusVideo { get; set; }
    }
}
