//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACT
    {
        public int id { get; set; }
        public string mapImage { get; set; }
        public string mapTitle { get; set; }
        public string mailadress { get; set; }
        public string adress { get; set; }
        public string telephone1 { get; set; }
        public string telephone2 { get; set; }
        public string telephone3 { get; set; }
        public string logoImage { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
