//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public string image { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string order { get; set; }
        public Nullable<bool> status { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
    }
}
