//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CUSTOMER_SQLEntities : DbContext
    {
        public CUSTOMER_SQLEntities()
            : base("name=CUSTOMER_SQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABOUT> ABOUT { get; set; }
        public virtual DbSet<CONTACT> CONTACT { get; set; }
        public virtual DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public virtual DbSet<ICONS> ICONS { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<NEWSLETTER> NEWSLETTER { get; set; }
        public virtual DbSet<SKILL> SKILL { get; set; }
        public virtual DbSet<SLIDER> SLIDER { get; set; }
        public virtual DbSet<SOCIALS> SOCIALS { get; set; }
        public virtual DbSet<WORK> WORK { get; set; }
    }
}
