//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIALS
    {
        public int id { get; set; }
        public string socialUrl { get; set; }
        public string socialName { get; set; }
        public string order { get; set; }
        public Nullable<bool> status { get; set; }
    }
}
