/// <autosync enabled="true" />
/// <reference path="../content/assets/js/frontend/address-i18n.min.js-ver=2.5.5.js" />
/// <reference path="../content/assets/js/frontend/add-to-cart.min.js-ver=2.5.5.js" />
/// <reference path="../content/assets/js/frontend/cart.min.js-ver=2.5.5.js" />
/// <reference path="../content/assets/js/frontend/cart-fragments.min.js-ver=2.5.5.js" />
/// <reference path="../content/assets/js/frontend/country-select.min.js-ver=2.5.5.js" />
/// <reference path="../content/assets/js/frontend/single-product.min.js-ver=2.5.5.js" />
/// <reference path="../content/assets/js/frontend/woocommerce.min.js-ver=2.5.5.js" />
/// <reference path="../content/assets/js/jquery-cookie/jquery.cookie.min.js-ver=1.4.1.js" />
/// <reference path="../content/assets/js/prettyphoto/jquery.prettyphoto.init.min.js-ver=2.5.5.js" />
/// <reference path="../content/includes/js/comment-reply.min.js" />
/// <reference path="../content/includes/js/hoverintent.min.js-ver=1.8.1.js" />
/// <reference path="../content/includes/js/jquery/jquery.js-ver=1.12.4.js" />
/// <reference path="../content/includes/js/jquery/jquery-migrate.min.js-ver=1.4.1.js" />
/// <reference path="../content/includes/js/wp-embed.min.js" />
/// <reference path="../content/js/jquery-1.8.2.min.js" />
/// <reference path="../content/js/slider.js" />
/// <reference path="../content/lite/js/bootstrap.min.js-ver=20120206.js" />
/// <reference path="../content/lite/js/html5.js" />
/// <reference path="../content/lite/js/jquery.knob.js-ver=20120206.js" />
/// <reference path="../content/lite/js/scrollreveal.js-ver=20120206.js" />
/// <reference path="../content/lite/js/smoothscroll.js-ver=20120206.js" />
/// <reference path="../content/lite/js/zerif.js-ver=20120206.js" />
/// <reference path="../content/megamenu/js/maxmegamenu.js-ver=2.1.5.js" />
/// <reference path="../content/megamenu/js/megamenu.js" />
/// <reference path="../content/pirate-forms/js/pirateformsobject.js" />
/// <reference path="../content/pirate-forms/js/scripts-general.js" />
/// <reference path="../content/slider/js/jquery-1.11.3.min.js" />
/// <reference path="../content/slider/js/jssor.slider-21.1.5.js" />
/// <reference path="../content/slider/js/jssor.slider-21.1.5.mini.js" />
/// <reference path="bootstrap.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.js" />
/// <reference path="jquery-1.10.2.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
